# Generated by Django 4.2.6 on 2023-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_airport_id_alter_country_flag_trendingplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='nationality_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
