# Generated by Django 4.2.6 on 2023-11-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_nationality_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='nationality_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=7, null=True)),
                ('end_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='countries.airport')),
                ('start_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='countries.airport')),
                ('trending_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.trendingplace')),
            ],
        ),
    ]
