# Generated by Django 4.2.6 on 2023-11-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_country_nationality_id_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='nationality_id',
        ),
        migrations.AddField(
            model_name='country',
            name='nationality',
            field=models.CharField(blank=True, help_text='like Egyption, etc..', null=True),
        ),
    ]
